@extends('layouts.home.main')

@section('title',"🏡 Home")

@section('content')   

 
<div id="particles-js">
      
      
      <!-- <div class="center-text" >

         <div class=" heading" style="position: relative; z-index: 1; ">
              log viewer
         </div>

         <div class=" intro-data"style="position: relative;">
              many
         </div>
  
         <div class="start-button"style="position: relative;">
           <center><a href=""> <img src="logo1.png" alt="" style="height: 80px;"></a></center>
         </div>

     </div> -->
     
     <div class="center-text">

         <h1 style="position: relative; top: 75px; left: 200px;">LogManager</h1>
         
         <p style="font-size:2.4 ;position: relative; top: 25px;">This project with an idea to help the developer what happen
              is developer does not have access to the production server 
              to see their logs only senior developers or we can say senior
               devops engineer have access only so what we want to automate and 
               create up plugin with the help of node js and the work of plugin 
               is for example we want to see laravel frontend log so the developer 
               has to come with the some credentials or we can say authentication key 
               to access the log that key will be generated by Project Manager.
</p>
         <center>
             <a href="{{ route('login') }}"> <img src="images/logo1.png" alt="" style="height: 80px; position: relative; top: 40px;"></a>
         </center>

     </div>
         <br>
         <br>
    
     </div> 
    
 </div>

 <div style="height: 10%; width: 100%; background-color: black;" >
     <center> <h1 style="color: aliceblue;"> Feature</h1> </center>
    </div>
     
     <div class="usage">

    <div class="card" id="item1" style="position: relative; top: 40px ;">
        <div style=" position: relative; background-color: rgb(246, 224, 195); width: 80%; left: 9%; ">
        <center><h5> Manage Developers </h5></center>
     </div>
        <img src="images/manage developer.jpg" alt="">
        <div class="title" style="width: 200px; "> Project Mangers Have the Power to Add Developers or remove them and assign their tasks.</div>
        
    </div>
    
    <div class="card" id="item1" style="position: relative; top: 20px ;">
     <div style=" position: relative; background-color: rgb(246, 224, 195); width: 80%; left: 9%; ">
     <center><h5> Logs Views</h5></center>
  </div>
     <img src="images/logsview.png" alt="">
     <div class="title" style="width: 200px; "> We need to Configure the Config File of the plugin which is in form of JSON basically to manage the keys.</div>
     
 </div>
 <div class="card" id="item2" style="position: relative; top: 30px ;">
     <div style=" position: relative; background-color: rgb(246, 224, 195); width: 80%; left: 9%; ">
     <center><h5> Plugin Setup </h5></center>
  </div>
     <img src="images/plugin setup.png" alt="">
     <div class="title" style="width: 200px; "> Devlopers Can able see the logs at the runtime where there application on production Server.</div>
     
 </div>
    
</div>

 @endsection         